// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClzBdjcKiNb_0I05erqBDzJwEwFDb-q9I',
    appId: '1:259336677684:web:234f1c04bb81aba94f1d61',
    messagingSenderId: '259336677684',
    projectId: 'product-authentication-6a9be',
    authDomain: 'product-authentication-6a9be.firebaseapp.com',
    storageBucket: 'product-authentication-6a9be.appspot.com',
    measurementId: 'G-BDZE0K32ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxviJuImUgKJ-3WVPfoWSDosUrsLDrefY',
    appId: '1:259336677684:android:e1b400a327183db54f1d61',
    messagingSenderId: '259336677684',
    projectId: 'product-authentication-6a9be',
    storageBucket: 'product-authentication-6a9be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhgQ3414ya9h54LVjfp1dvLQltKpuW52c',
    appId: '1:259336677684:ios:7daa0726e55752584f1d61',
    messagingSenderId: '259336677684',
    projectId: 'product-authentication-6a9be',
    storageBucket: 'product-authentication-6a9be.appspot.com',
    iosClientId:
        '259336677684-bifjmsm0u205hsip6gtbkh7nmajfartp.apps.googleusercontent.com',
    iosBundleId: 'com.example.productVerification',
  );
}
